<?php

    $helperData = $this->helper('LogosCorp\CustomRegistration\Helper\Data');
    $configPage = $helperData->getTermsConfig();
?>
<div class="field choice terms required">
    <input type="checkbox"
        name="terms_and_conditions"
        title="<?= $escaper->escapeHtmlAttr(__('I accept the terms and conditions')) ?>"
        value="1"
        id="terms_and_conditions"
        class="checkbox required"
        data-validate="{required:true}"
        <?= ($block->getCustomer() && $block->getCustomer()->getCustomAttribute('terms_and_conditions')->getValue()) ? 'checked="checked"' : null; ?>
    >
    <label for="terms_and_conditions" class="label">
        <?php if ($configPage): ?>
            <a href="<?= $this->getUrl($configPage) ?>" target="_blank"><?= $escaper->escapeHtml(__('Acepto los términos y condiciones')) ?></a>
        <?php else: ?>
            <span><?= $escaper->escapeHtml(__('I accept the terms and conditions')) ?></span>
        <?php endif ?>
    </label>
</div>